### ISSUE TITLE
Almost all success purchases are obtained with Restored status on Android

### ISSUE THREAD

**Issue by gestern** [newnon/avalon#3]
I'm a little bit confused with the code under Android:
https://github.com/newnon/avalon/blob/bfed8b03422afcdba5a0d9d96baceff156c91697/avalon/platform/android/payment/payment.cpp#L238

As a result, almost all success purchases are obtained with the status `Restored` not `Purchased`. So it should be or is it a bug?

**Comment by gestern** [comment]
I prepared a patch, could you review it and roll it back if it is incorrect.

**Comment by newnon** [comment]
fixed
